### ISSUE TITLE
level constructor

### ISSUE THREAD

**Issue by kolganovn** [python-practice-b02-006/magnetic-pool#5]
Attempt to create a level without some ingredient (pool or ball) leads to a crash of the app.
How to create an obstacle inside the main field?

**Comment by d-khromov** [comment]
Fixed this bug in 48f4703badcd34aa75b8b73137c257b27c30f6ca. Now player can only move to the next stage if he has completed the previous one.
In order to create an obstacle you should press "space" button after you have created the edges of the table. Then you right click to make vertices as usual. When you are done you can press "space" button again and create other obstacles.

P.S. 
Hopefully there will be instructions in the game soon.
